[package]
name = "btunel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bufstream = { version = "0.1.4" }
crossbeam = "0.8.2"